get:
  tags:
    - "Products"
  summary: "Get one product."
  description: "Get one product."
  operationId: "getProductById"
  parameters:
    - $ref: "#/components/parameters/RefArticle"
    - $ref: "#/components/parameters/Deleted"
  responses:
    200:
      description: "Request OK."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Products"
    400:
      $ref: "#/components/responses/400"
    401:
      $ref: "#/components/responses/401"
    404:
      $ref: "#/components/responses/404"
    405:
      $ref: "#/components/responses/405"
  x-swagger-router-controller: "Products"
  security:
    - api_key: []
    - bearer_auth: []
    - main_auth:
      - 'read:product'
