openapi: 3.0.0
info:
  version: 1.0.0
  title: Ravimoshark Piece API
  termsOfService: 'https://ravimoshark.com/terms/'
  contact:
    email: dev@ravimoshark.com
    url: 'http://ravimoshark.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  description: >
    This is an API to interact with Ravimoshark piece database.

    # Introduction

    This API allow to create, modify and delete pieces and products (cards, details and key points).

    # User Authentication

    This API does not contain any kind of user validation but It request to have
    a valid authentication user to interact with it.
    For more information about user Authentication, please refer to
    [Ravimoshark User Authentication](https://ravimoshark.com/back/apis/auth/latest).
externalDocs:
  description: Find out how to interact with Ravimoshark's APIs.
  url: 'https://ravimoshark.com/back/apis/auth/latest'
tags:
  - name: Products
    description: Operations about products.
  - name: Categories
    description: Operations about categories.
  - name: Pieces
    description: Operations about pieces.
servers:
  - url: 'http://localhost:8000'
  - url: 'https://ravimoshark.com/back/apis/piece/v1'
  - url: 'https://ravimoshark.com/back/apis/piece/latest'
